package rulesTwo.isFlow.flowNameNotSame

rule "测试规则流参数不相同规则1"
ruleflow-group "FlowNameNotSame1"
activation-group "actSame"
    when
    then
        System.out.println(drools.getRule().getName());
end

rule "测试规则流参数不相同规则2"
ruleflow-group "FlowNameNotSame2"
activation-group "actSame"
    when
    then
        System.out.println(drools.getRule().getName());
end

rule "未设置规则流参数的规则"
    when
    then
        System.out.println(drools.getRule().getName());
end
