package testKieSessionPool;

import com.pojo.Person;


rule "testKieSessionPool"
    when
        $p:Person(0<age , age<3 ,$d:(age/dous),$d>0,$d<0.6)
    then
         //System.out.println($d+"---"+drools.getRule().getName());
         //System.out.println("不稳定");
end

rule "testKieSessionPool_1"
    when
        $p:Person(0<age , age<3 ,$d:(age/dous),$d>=0.5,$d<1)
    then
        //System.out.println($d+"---"+drools.getRule().getName());
         //System.out.println("稳定");
end

rule "testKieSessionPool_2"
    when
        $p:Person(0<age , age<3 ,$d:(age/dous),$d>=1)
    then
        //System.out.println($d+"---"+drools.getRule().getName());
         //System.out.println("良好");
end
