package rules.constraint.isStr;

import com.pojo.Person;

rule strTest001
    when
        $p:Person(name str[startsWith] "张");
    then
      System.out.println("恭喜你，成功的使用了 str startsWith");
end


rule strTest002
    when
         $p:Person(name str[endsWith] "三");
    then
       System.out.println("恭喜你，成功的使用了 str endsWith");
end


rule strTest003
    when
         $p:Person(name str[length] 3);
    then
      System.out.println("恭喜你，成功的使用了 str length");
end