package rules.isIn
import com.pojo.Person;
import com.pojo.School;

rule "in的复合规则"
    when
        School($cn:className)
        Person(className in("五班","六班",$cn) )
    then
        System.out.println("验证in的复合限制规则");
end

rule "not in的复合规则"
    when
        School($cn:className)
        Person(className not in("五班","六班",$cn) )
    then
        System.out.println("验证not in的复合限制规则");
end


rule "使用 && 做多限制"
    when
       Person( age > 30 && < 40 )
    then
        System.out.println("使用 && 做多限制");
end

rule "使用 ， 做多限制"
    when
       Person( age > 30 && < 40 )
    then
        System.out.println("使用 ， 做多限制");
end