package rules.isDeclare

declare PersonEx extends com.pojo.Person
    type:String
end

rule "declareInsertExt"
    when
    then
        PersonEx p=new PersonEx();
        p.setType("1");
        p.setAge(20);
        p.setName("张三");
        insert(p);
end

rule "declareTestExtends"
    when
        $p:PersonEx(name=="张三")
    then
       System.out.println("输出PersonEx的name"+$p.getName());
       System.out.println("输出PersonEx的age"+$p.getAge());
       System.out.println("输出PersonEx的type"+$p.getType());
end