package rulesTwo.Listener
import com.pojo.Person;

rule "测试Insert"
no-loop true
    when
    then
        Person person=new Person("张三",50);
        insert(person);
       System.out.println(drools.getRule().getName());
end

rule "测试Update"
no-loop true
    when
        $p:Person(name=="张三")
    then
       modify($p){
       setName("李四")
       }
       System.out.println(drools.getRule().getName());
end

rule "测试Delete"
no-loop true
    when
        $p:Person(name=="李四")
    then
       delete($p);
       System.out.println(drools.getRule().getName());
end



rule "测试匹配不上的规则"
no-loop true
    when
        $p:Person(name=="李四")
    then
       System.out.println(drools.getRule().getName());
end